/*=============================================================================
	ALAudioNames.h - Used for autogenerated names.
=============================================================================*/

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (push,OBJECT_ALIGNMENT)
#endif

#ifndef ALAUDIO_API
#define ALAUDIO_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern ALAUDIO_API FName ALAUDIO_##name;
#endif

/*-----------------------------------------------------------------------------
	Names.
-----------------------------------------------------------------------------*/

// UnrealScript Events.
#ifdef EFX
AUTOGENERATE_NAME(QueryEffects)
#endif

// Intended as Log Tags.
AUTOGENERATE_NAME(ALAudio)
AUTOGENERATE_NAME(OpenAL)
AUTOGENERATE_NAME(XMP)

/*----------------------------------------------------------------------------
	Ugly macros go here.
----------------------------------------------------------------------------*/

#define NAME_ALAudio	((EName)(ALAUDIO_ALAudio.GetIndex()))
#define NAME_OpenAL		((EName)(ALAUDIO_OpenAL.GetIndex()))
#define NAME_EFX		((EName)(ALAUDIO_EFX.GetIndex()))
#define NAME_XMP		((EName)(ALAUDIO_XMP.GetIndex()))

/*-----------------------------------------------------------------------------
  End of Names.
-----------------------------------------------------------------------------*/

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#endif // NAMES_ONLY

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (pop)
#endif

/*-----------------------------------------------------------------------------
	The End.
-----------------------------------------------------------------------------*/
