	AMover();
	void PostLoad();
	void PostEditChange();
	void Spawned();
	void PostEditMove();
	void PreRaytrace();
	void Modify();
	void PreNetReceive();
	void PostNetReceive();
	void NotifyActorMoved();
	void performPhysics(FLOAT DeltaSeconds);
	void physMovingBrush(FLOAT DeltaTime);
	void PostRaytrace(FThreadLock& Mutex);
	void TransformPermanently( BYTE KeepRotation );
	void PostBeginPlay();
	virtual void SetWorldRaytraceKey();
	virtual void SetBrushRaytraceKey();
	void CopyPosRotScaleFrom(ABrush* Other);
	virtual INT* NativeReplicationRep(NETCOND_PARAMS);
	FStaticLightActor* GetStaticLights();
	UBOOL IsValidOnImport();
	bool ShouldTrace( DWORD TraceFlags, AActor* SourceActor );
	void PostScriptDestroyed();
	void setPhysics(BYTE NewPhysics, AActor* NewFloor = NULL);
	UBOOL ShouldExportProperty(UProperty* Property) const;
	void Serialize(FArchive& Ar);
	void RenderSelectInfo(FSceneNode* Frame);
	UBOOL IsDynamicBSP() const;
